export const assets: Array<{ name: string; url: string }> = [
  // LEVEL
  { name: "Level 1", url: "/assets/levels/1.json" },
  { name: "Tutorial 1", url: "/assets/levels/tutorial-1.json" },
  { name: "render test", url: "/assets/levels/render-test.json" },
  { name: "Fisher 1", url: "/assets/levels/Fisher 1.json" },
  // UI
  { name: "button", url: "/assets/sprites/ui/button.png" },
  { name: "buttonHover", url: "/assets/sprites/ui/buttonHover.png" },
  { name: "buttonLock", url: "/assets/sprites/ui/buttonLock.png" },
  { name: "buttonSound", url: "/assets/sounds/ui/button.mp3" },
  { name: "buttonSelectTile", url: "/assets/sprites/ui/buttonSelectTile.png" },
  {
    name: "buttonSelectTileHover",
    url: "/assets/sprites/ui/buttonSelectTileHover.png",
  },
  //#region SPRITES
  { name: "fisher", url: "/assets/sprites/entities/fisher.png" },
  //#endregion
  //#region TERRAIN
  { name: "emptyTile", url: "/assets/sprites/terrain/emptyTile.png" },
  { name: "emptyTileHover", url: "/assets/sprites/terrain/emptyTileHover.png" },
  { name: "blockedTile0", url: "/assets/sprites/terrain/empty_0.png" },
  { name: "blockedTile1", url: "/assets/sprites/terrain/empty_1.png" },
  { name: "blockedTile2", url: "/assets/sprites/terrain/empty_2.png" },
  { name: "blockedTile3", url: "/assets/sprites/terrain/empty_3.png" },
  { name: "riverEnd0", url: "/assets/sprites/terrain/river-end_0.png" },
  { name: "riverEnd1", url: "/assets/sprites/terrain/river-end_1.png" },
  { name: "riverEnd2", url: "/assets/sprites/terrain/river-end_2.png" },
  { name: "riverEnd3", url: "/assets/sprites/terrain/river-end_3.png" },
  { name: "riverBendy0", url: "/assets/sprites/terrain/river-bendy_0.png" },
  { name: "riverBendy1", url: "/assets/sprites/terrain/river-bendy_1.png" },
  { name: "riverBendy2", url: "/assets/sprites/terrain/river-bendy_2.png" },
  { name: "riverBendy3", url: "/assets/sprites/terrain/river-bendy_3.png" },
  { name: "riverCross0", url: "/assets/sprites/terrain/river-cross_0.png" },
  { name: "riverCross1", url: "/assets/sprites/terrain/river-cross_1.png" },
  { name: "riverCross2", url: "/assets/sprites/terrain/river-cross_2.png" },
  { name: "riverCross3", url: "/assets/sprites/terrain/river-cross_3.png" },
  {
    name: "riverStraight0",
    url: "/assets/sprites/terrain/river-straight_0.png",
  },
  {
    name: "riverStraight1",
    url: "/assets/sprites/terrain/river-straight_1.png",
  },
  {
    name: "riverStraight2",
    url: "/assets/sprites/terrain/river-straight_2.png",
  },
  {
    name: "riverStraight3",
    url: "/assets/sprites/terrain/river-straight_3.png",
  },
  { name: "riverT0", url: "/assets/sprites/terrain/river-t_0.png" },
  { name: "riverT1", url: "/assets/sprites/terrain/river-t_1.png" },
  { name: "riverT2", url: "/assets/sprites/terrain/river-t_2.png" },
  { name: "riverT3", url: "/assets/sprites/terrain/river-t_3.png" },
  { name: "lake", url: "/assets/sprites/terrain/lake.png" },
  //#endregion
  //#region decoration
  { name: "redFlower0", url: "/assets/sprites/decoration/redFlower0.png"},
  { name: "redFlower1", url: "/assets/sprites/decoration/redFlower1.png"},
  { name: "redFlower2", url: "/assets/sprites/decoration/redFlower2.png"},
  { name: "redFlower3", url: "/assets/sprites/decoration/redFlower3.png"},
  { name: "shrub1-0", url: "/assets/sprites/decoration/shrub1-0.png"},
  { name: "shrub1-1", url: "/assets/sprites/decoration/shrub1-1.png"},
  { name: "shrub1-2", url: "/assets/sprites/decoration/shrub1-2.png"},
  { name: "shrub1-3", url: "/assets/sprites/decoration/shrub1-3.png"},
  { name: "grass1-0", url: "/assets/sprites/decoration/grass1-0.png"},
  { name: "grass1-1", url: "/assets/sprites/decoration/grass1-1.png"},
  { name: "grass1-2", url: "/assets/sprites/decoration/grass1-2.png"},
  { name: "grass1-3", url: "/assets/sprites/decoration/grass1-3.png"},
  { name: "grass2-0", url: "/assets/sprites/decoration/grass2-0.png"},
  { name: "grass2-1", url: "/assets/sprites/decoration/grass2-1.png"},
  { name: "grass2-2", url: "/assets/sprites/decoration/grass2-2.png"},
  { name: "grass2-3", url: "/assets/sprites/decoration/grass2-3.png"},
  { name: "stoneFlat0", url: "/assets/sprites/decoration/stoneFlat0.png"},
  { name: "stoneFlat1", url: "/assets/sprites/decoration/stoneFlat1.png"},
  { name: "stoneFlat2", url: "/assets/sprites/decoration/stoneFlat2.png"},
  { name: "stoneFlat3", url: "/assets/sprites/decoration/stoneFlat3.png"},
  { name: "yellowMushroom0", url: "/assets/sprites/decoration/yellowMushroom0.png"},
  { name: "yellowMushroom1", url: "/assets/sprites/decoration/yellowMushroom1.png"},
  { name: "yellowMushroom2", url: "/assets/sprites/decoration/yellowMushroom2.png"},
  { name: "yellowMushroom3", url: "/assets/sprites/decoration/yellowMushroom3.png"},
  { name: "pebble0", url: "/assets/sprites/decoration/pebble0.png"},
  { name: "pebble1", url: "/assets/sprites/decoration/pebble1.png"},
  { name: "pebble2", url: "/assets/sprites/decoration/pebble2.png"},
  { name: "pebble3", url: "/assets/sprites/decoration/pebble3.png"},
  
  //#endregion
];
